# Source build of the Electron launcher GUI of codex-chatgpt-web — the main
# package. The daemon CLI lives next door in packages/codex-chatgpt-web-cli
# and shares this directory's hashes.json + bun.nix: one update (update.py)
# moves both, and the CLI asserts version equality with this derivation at
# eval time. The CLI is exposed here as passthru.cli and in
# update-companions so CI updates it in lockstep.
#
# Upstream packages the launcher with electron-builder and ships a bundled bun
# runtime (launcher build:runtime -> scripts/build-runtime-bundle.ts). We skip
# all of that and run the launcher UNPACKAGED instead: nixpkgs electron_41
# loading $out/share/codex-chatgpt-web/launcher directly.
#
# In unpackaged mode (app.isPackaged = false) launcher/electron/main.cjs:
#   * loads the renderer from ../dist/index.html — prebuilt here with vite
#     (launcher build:renderer; base "./" keeps the file:// URL working);
#   * spawns the CLI runtime via sourceRuntimeInvocation
#     (launcher/electron/runtime-command.cjs): "$CODEX_WEB_GPT_BUN" run
#     <SOURCE_ROOT>/src/cli.ts ... — pointed at plain nixpkgs bun, NOT the
#     flake's codex-chatgpt-web-cli bin wrapper (which appends its own cli.ts
#     argument);
#   * resolves the browser helper from SOURCE_ROOT/.launcher-runtime/
#     browser-helper.cjs. That file is a DEV-TIME artifact generated by
#     upstream's scripts/build-browser-helper.ts (launcher/scripts/dev.cjs
#     builds it before starting electron; nothing regenerates it at runtime).
#     We pre-generate it during the build and ship it read-only in the store;
#     its externalized "playwright-core" import resolves from the root
#     node_modules shipped alongside.
#
# All writable state lands in user directories via resolveLauncherProfile
# (launcher/electron/profile.cjs): ~/.codex-chatgpt-web (coreHome),
# <appData>/Codex Web GPT (userData) and ~/.codex (codexHome) — the unpackaged
# run gets the regular production profile, so nothing ever writes into the
# store path.
{
  lib,
  stdenvNoCC,
  fetchFromGitHub,
  bun,
  bun2nixLib,
  electron_41,
  makeWrapper,
  flake,
  codex-chatgpt-web-cli,
}:

let
  versionData = builtins.fromJSON (builtins.readFile ./hashes.json);
  inherit (versionData) version hash;
in
stdenvNoCC.mkDerivation (finalAttrs: {
  pname = "codex-chatgpt-web";
  inherit version;

  src = fetchFromGitHub {
    owner = "miuuyy";
    repo = "codex-chatgpt-web";
    tag = "v${finalAttrs.version}";
    inherit hash;
  };

  nativeBuildInputs = [
    bun2nixLib.hook
    makeWrapper
  ];

  # Root project deps (src/cli.ts runtime tree). Production only — the
  # browser-helper bundling step needs nothing beyond prod deps + bun
  # builtins. The hook installs these into the root of the source tree.
  bunDeps = bun2nixLib.fetchBunDeps { bunNix = ./bun.nix; };
  # launcher/ deps (react runtime + vite/electron devDeps for the renderer
  # build). Fetched as a second offline cache and merged into
  # BUN_INSTALL_CACHE_DIR in buildPhase — bun's cache is content-addressed,
  # so both trees coexist in one cache dir. Both bun.nix (root) and
  # bun-launcher.nix (launcher) are regenerated by this package's update.py.
  launcherBunDeps = bun2nixLib.fetchBunDeps { bunNix = ./bun-launcher.nix; };

  # --production keeps @types/* and typescript out of the runtime tree; the
  # hook always appends --ignore-scripts, so electron's postinstall binary
  # download never runs in the sandbox.
  bunInstallFlags = [
    "--linker=isolated"
    "--production"
  ];
  dontRunLifecycleScripts = true;
  # Custom build below (vite renderer + browser helper), no `bun build`.
  dontUseBunBuild = true;

  env = {
    CI = "1";
    ELECTRON_SKIP_BINARY_DOWNLOAD = "1";
  };

  buildPhase = ''
    runHook preBuild

    # Merge the launcher's offline cache next to the root cache the hook
    # already populated during bunNodeModulesInstallPhase. The hook's copy
    # leaves directories with read-only store permissions; make them
    # writable first so cp can descend into them and bun can update its
    # cache bookkeeping.
    chmod -R u+w "$BUN_INSTALL_CACHE_DIR"
    cp -r "$launcherBunDeps"/share/bun-cache/. "$BUN_INSTALL_CACHE_DIR"/
    chmod -R u+w "$BUN_INSTALL_CACHE_DIR"

    # Launcher deps including devDependencies (vite, @vitejs/plugin-react,
    # typescript). --ignore-scripts again skips electron's binary download.
    (
      cd launcher
      bun install --linker=isolated --ignore-scripts
    )

    # Bundle the browser helper exactly where the unpackaged launcher looks
    # for it (SOURCE_ROOT/.launcher-runtime/browser-helper.cjs, main.cjs).
    bun run scripts/build-browser-helper.ts

    # Renderer: vite bundle into launcher/dist/index.html.
    (
      cd launcher
      bun run build:renderer
    )

    # The launcher main process only requires the electron built-in and its
    # local .cjs modules, and the renderer is fully bundled — prune the
    # launcher devDependencies (electron, electron-builder, vite) from the
    # tree we ship. bun will not uninstall already-present devDeps, so start
    # over with a production-only install from the same offline cache.
    (
      cd launcher
      rm -rf node_modules
      bun install --linker=isolated --ignore-scripts --production
    )

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    install -d $out/share/codex-chatgpt-web
    # SOURCE_ROOT as main.cjs resolves it (__dirname/../..): the root project
    # next to launcher/, with the prebuilt renderer inside launcher/dist.
    cp -r src node_modules package.json tsconfig.json .launcher-runtime launcher \
      $out/share/codex-chatgpt-web/

    install -Dm644 launcher/assets/icon.png \
      $out/share/icons/hicolor/512x512/apps/codex-chatgpt-web.png

    # Unpackaged launcher run. --no-sandbox: Chromium's setuid sandbox cannot
    # live in the (immutable) nix store — repo precedent (paseo-desktop).
    # CODEX_WEB_GPT_BUN selects the bun binary sourceRuntimeInvocation spawns
    # for the CLI runtime.
    makeWrapper ${lib.getExe electron_41} $out/bin/codex-chatgpt-web \
      --add-flags "$out/share/codex-chatgpt-web/launcher" \
      --add-flags "--no-sandbox" \
      --set CODEX_WEB_GPT_BUN "${lib.getExe bun}" \
      --prefix PATH : "${lib.makeBinPath [ bun ]}"

    runHook postInstall
  '';

  doInstallCheck = true;
  # Structural checks only: this is a GUI — never launch it from the builder.
  installCheckPhase = ''
    runHook preInstallCheck

    test -x $out/bin/codex-chatgpt-web
    test -f $out/share/codex-chatgpt-web/launcher/dist/index.html
    test -f $out/share/codex-chatgpt-web/launcher/electron/main.cjs
    test -d $out/share/codex-chatgpt-web/node_modules
    test -d $out/share/codex-chatgpt-web/launcher/node_modules
    test -f $out/share/codex-chatgpt-web/.launcher-runtime/browser-helper.cjs

    runHook postInstallCheck
  '';

  passthru.category = "AI Coding Agents";
  # The CLI shares this package's source and version (see
  # packages/codex-chatgpt-web-cli/package.nix).
  passthru.cli = codex-chatgpt-web-cli;

  meta = {
    description = "Electron launcher for codex-chatgpt-web: use ChatGPT Web (including Pro) as native Codex models";
    homepage = "https://github.com/miuuyy/codex-chatgpt-web";
    changelog = "https://github.com/miuuyy/codex-chatgpt-web/releases/tag/v${finalAttrs.version}";
    license = lib.licenses.mit;
    sourceProvenance = [ lib.sourceTypes.fromSource ];
    maintainers = with flake.lib.maintainers; [ smdex ];
    mainProgram = "codex-chatgpt-web";
    platforms = [ "x86_64-linux" ];
  };
})
